hops

id
name
country (ISO3)
description
usage (bittering, aroma, both)
hop_storage_index
alpha_acid_percentage_max
alpha_acid_percentage_min
beta_acid_percentage_max
beta_acid_percentage_min

??
co_humolone_percentage
total_oil_percentage
b_pinene_percentage
myrcene_percentage
linalool_percentage
caryophyllene_percentage
farnesene_percentage
humulene_percentage
geraniol_percentage
